apiVersion : apps/v1
kind: Deployment
metadata:
  name: dstncalcapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dstncalcapi
  template:
    metadata:
      labels:
        app: dstncalcapi 
    spec:
      containers:
        - name: dstncalcapi 
          image: containerregistry4pd7i.azurecr.io/dstncalcapi
          ports:
          - containerPort: 80