---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: develop
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "develop.covercrop-ncalc.org"
    secretName: ncalc
  rules:
  - host: "develop.covercrop-ncalc.org"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: precisionsustainableagccn
              port:
                number: 1002
        - pathType: Prefix
          path: "/*"
          backend:
            service:
              name: precisionsustainableagccn
              port:
                number: 1002